/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GraphMetricsHeatmapPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/color.ts
function parseHexColor(value) {
  const hex = value.trim().replace(/^#/, "");
  if (!/^[0-9a-fA-F]+$/.test(hex)) return null;
  if (hex.length === 3) {
    return {
      r: parseInt(hex[0] + hex[0], 16),
      g: parseInt(hex[1] + hex[1], 16),
      b: parseInt(hex[2] + hex[2], 16)
    };
  }
  if (hex.length === 6) {
    return {
      r: parseInt(hex.slice(0, 2), 16),
      g: parseInt(hex.slice(2, 4), 16),
      b: parseInt(hex.slice(4, 6), 16)
    };
  }
  return null;
}
function toTint({ r, g, b }) {
  return clampByte(r) << 16 | clampByte(g) << 8 | clampByte(b);
}
function mix(from, to, amount) {
  const t = Math.min(1, Math.max(0, amount));
  return {
    r: Math.round(from.r + (to.r - from.r) * t),
    g: Math.round(from.g + (to.g - from.g) * t),
    b: Math.round(from.b + (to.b - from.b) * t)
  };
}
function gradientTint(cold, hot, intensity) {
  return toTint(mix(cold, hot, intensity));
}
function clampByte(value) {
  return Math.min(255, Math.max(0, Math.round(value)));
}

// src/types.ts
var DEFAULT_SETTINGS = {
  enabled: true,
  coldColor: "#3b6fd4",
  hotColor: "#e8452c",
  days: null,
  source: "all",
  scale: "log",
  refreshSeconds: 30
};
var HOST_PLUGIN_ID = "obsidian-local-rest-api";
var METRICS_FILE_NAME = "metrics.json";

// src/graphColorizer.ts
var GRAPH_VIEW_TYPES = ["graph", "localgraph"];
var UNCOLOURABLE_NODE_TYPES = /* @__PURE__ */ new Set(["tag", "unresolved"]);
var GraphColorizer = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
    this.intensities = /* @__PURE__ */ new Map();
    this.original = /* @__PURE__ */ new WeakMap();
    this.painted = false;
  }
  setIntensities(intensities2) {
    this.intensities = intensities2;
    this.apply();
  }
  /** Number of notes the current data set can colour. */
  get coloured() {
    return this.intensities.size;
  }
  apply() {
    var _a, _b, _c, _d, _e;
    const settings = this.settings();
    if (!settings.enabled) {
      this.clear();
      return;
    }
    const cold = (_a = parseHexColor(settings.coldColor)) != null ? _a : parseHexColor(DEFAULT_SETTINGS.coldColor);
    const hot = (_b = parseHexColor(settings.hotColor)) != null ? _b : parseHexColor(DEFAULT_SETTINGS.hotColor);
    for (const renderer of this.renderers()) {
      let changed = false;
      for (const node of (_c = renderer.nodes) != null ? _c : []) {
        const circle = node.circle;
        if (!circle || typeof node.id !== "string") continue;
        if (typeof node.type === "string" && UNCOLOURABLE_NODE_TYPES.has(node.type)) {
          continue;
        }
        const intensity = (_d = this.intensities.get(node.id)) != null ? _d : 0;
        const tint = gradientTint(cold, hot, intensity);
        if (!this.original.has(circle)) this.original.set(circle, circle.tint);
        if (circle.tint !== tint) {
          circle.tint = tint;
          changed = true;
        }
      }
      if (changed) (_e = renderer.changed) == null ? void 0 : _e.call(renderer);
    }
    this.painted = true;
  }
  /** Restores the colours the renderer had chosen for every node still on screen. */
  clear() {
    var _a, _b;
    if (!this.painted) return;
    this.painted = false;
    for (const renderer of this.renderers()) {
      let changed = false;
      for (const node of (_a = renderer.nodes) != null ? _a : []) {
        const circle = node.circle;
        if (!circle) continue;
        const original = this.original.get(circle);
        if (original === void 0 || circle.tint === original) continue;
        circle.tint = original;
        changed = true;
      }
      if (changed) (_b = renderer.changed) == null ? void 0 : _b.call(renderer);
    }
  }
  *renderers() {
    var _a;
    for (const type of GRAPH_VIEW_TYPES) {
      for (const leaf of this.app.workspace.getLeavesOfType(type)) {
        const renderer = (_a = leaf.view) == null ? void 0 : _a.renderer;
        if (renderer && Array.isArray(renderer.nodes)) yield renderer;
      }
    }
  }
};

// src/metrics.ts
function metricsStorePath(app) {
  return `${app.vault.configDir}/plugins/${HOST_PLUGIN_ID}/${METRICS_FILE_NAME}`;
}
async function readMetricsStore(app) {
  const path = metricsStorePath(app);
  try {
    if (!await app.vault.adapter.exists(path)) return null;
    return parseMetricsData(JSON.parse(await app.vault.adapter.read(path)));
  } catch (e) {
    return null;
  }
}
function dayKey(at) {
  const month = `${at.getMonth() + 1}`.padStart(2, "0");
  const day = `${at.getDate()}`.padStart(2, "0");
  return `${at.getFullYear()}-${month}-${day}`;
}
function parseMetricsData(parsed) {
  if (typeof parsed !== "object" || parsed === null) return null;
  const candidate = parsed;
  if (candidate.version !== 1) return null;
  if (typeof candidate.notes !== "object" || candidate.notes === null) return null;
  const notes = {};
  for (const [path, note] of Object.entries(candidate.notes)) {
    if (typeof note !== "object" || note === null) continue;
    const entry = note;
    if (typeof entry.total !== "number") continue;
    notes[path] = {
      total: entry.total,
      reads: numberOr(entry.reads),
      writes: numberOr(entry.writes),
      deletes: numberOr(entry.deletes),
      mcp: numberOr(entry.mcp),
      rest: numberOr(entry.rest),
      firstAccess: typeof entry.firstAccess === "string" ? entry.firstAccess : "",
      lastAccess: typeof entry.lastAccess === "string" ? entry.lastAccess : "",
      daily: dailyOf(entry.daily)
    };
  }
  return {
    version: 1,
    collectingSince: typeof candidate.collectingSince === "string" ? candidate.collectingSince : "",
    notes
  };
}
function noteTotals(data, window2) {
  const cutoffKey = window2.days === null || window2.days <= 0 ? null : dayKey(startOfDayBefore(Math.floor(window2.days) - 1));
  const totals = /* @__PURE__ */ new Map();
  for (const [path, note] of Object.entries(data.notes)) {
    let windowed = note.total;
    if (cutoffKey !== null) {
      windowed = 0;
      for (const [key, count] of Object.entries(note.daily)) {
        if (key >= cutoffKey) windowed += count;
      }
    }
    const share = window2.source === "all" ? 1 : note.total > 0 ? (window2.source === "mcp" ? note.mcp : note.rest) / note.total : 0;
    const total = Math.round(windowed * share);
    if (total > 0) totals.set(path, total);
  }
  return totals;
}
function intensities(data, window2) {
  const totals = noteTotals(data, window2);
  let max = 0;
  for (const total of totals.values()) max = Math.max(max, total);
  if (max === 0) return /* @__PURE__ */ new Map();
  const result = /* @__PURE__ */ new Map();
  const logMax = Math.log1p(max);
  for (const [path, total] of totals) {
    result.set(
      path,
      window2.scale === "log" ? Math.log1p(total) / logMax : total / max
    );
  }
  return result;
}
function numberOr(value) {
  return typeof value === "number" && Number.isFinite(value) ? value : 0;
}
function dailyOf(value) {
  if (typeof value !== "object" || value === null) return {};
  const daily = {};
  for (const [key, count] of Object.entries(value)) {
    if (typeof count === "number" && Number.isFinite(count)) daily[key] = count;
  }
  return daily;
}
function startOfDayBefore(days) {
  const at = /* @__PURE__ */ new Date();
  at.setHours(0, 0, 0, 0);
  at.setDate(at.getDate() - days);
  return at;
}

// src/settings.ts
var import_obsidian = require("obsidian");
var HeatmapSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, host) {
    super(app, host);
    this.host = host;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const settings = this.host.settings;
    const save = async (repaint = true) => {
      await this.host.saveSettings();
      if (repaint) await this.host.reload(false);
    };
    new import_obsidian.Setting(containerEl).setName("Enable heat map").setDesc(
      "Colour graph nodes by how often each note was accessed through Local REST API with MCP."
    ).addToggle(
      (toggle) => toggle.setValue(settings.enabled).onChange(async (value) => {
        settings.enabled = value;
        await save();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Window").setHeading();
    new import_obsidian.Setting(containerEl).setName("Days").setDesc("Only count accesses from the last N days. 0 counts the whole history.").addText(
      (text) => text.setPlaceholder("0").setValue(settings.days === null ? "0" : `${settings.days}`).onChange(async (value) => {
        const days = Number.parseInt(value, 10);
        settings.days = Number.isFinite(days) && days > 0 ? days : null;
        await save();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Source").setDesc("Only count accesses that arrived over this surface.").addDropdown(
      (dropdown) => dropdown.addOptions({ all: "REST and MCP", rest: "REST only", mcp: "MCP only" }).setValue(settings.source).onChange(async (value) => {
        settings.source = value;
        await save();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Scale").setDesc(
      "Access counts are usually dominated by a handful of notes; a logarithmic curve keeps the rest distinguishable."
    ).addDropdown(
      (dropdown) => dropdown.addOptions({ log: "Logarithmic", linear: "Linear" }).setValue(settings.scale).onChange(async (value) => {
        settings.scale = value === "linear" ? "linear" : "log";
        await save();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Refresh interval").setDesc("Seconds between re-reads of the metrics store.").addText(
      (text) => text.setPlaceholder(`${DEFAULT_SETTINGS.refreshSeconds}`).setValue(`${settings.refreshSeconds}`).onChange(async (value) => {
        const seconds = Number.parseInt(value, 10);
        settings.refreshSeconds = Number.isFinite(seconds) && seconds >= 5 ? seconds : DEFAULT_SETTINGS.refreshSeconds;
        await save();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Colours").setHeading();
    new import_obsidian.Setting(containerEl).setName("Least accessed").setDesc("Also the colour of notes with no recorded access.").addColorPicker(
      (picker) => picker.setValue(settings.coldColor).onChange(async (value) => {
        settings.coldColor = value;
        await save();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Most accessed").addColorPicker(
      (picker) => picker.setValue(settings.hotColor).onChange(async (value) => {
        settings.hotColor = value;
        await save();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Data").setHeading();
    const status = new import_obsidian.Setting(containerEl).setName("Metrics store").setDesc(this.host.status());
    status.addButton(
      (button) => button.setButtonText("Reload now").onClick(async () => {
        await this.host.reload(true);
        status.setDesc(this.host.status());
      })
    );
  }
};

// src/main.ts
var GraphMetricsHeatmapPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.reloadTimer = null;
    this.repaintHandle = null;
    this.lastStatus = "Not loaded yet.";
  }
  async onload() {
    await this.loadSettings();
    this.colorizer = new GraphColorizer(this.app, () => this.settings);
    this.addSettingTab(new HeatmapSettingTab(this.app, this));
    this.addCommand({
      id: "reload-metrics",
      name: "Reload metrics and recolour the graph",
      callback: () => void this.reload(true)
    });
    this.addCommand({
      id: "toggle-heatmap",
      name: "Toggle the metrics heat map",
      callback: () => {
        this.settings.enabled = !this.settings.enabled;
        void this.saveSettings().then(() => this.reload(false));
        new import_obsidian2.Notice(`Metrics heat map ${this.settings.enabled ? "on" : "off"}`);
      }
    });
    this.startRepaintLoop();
    this.app.workspace.onLayoutReady(() => void this.reload(false));
    this.scheduleReload();
  }
  onunload() {
    var _a;
    this.stopReloadTimer();
    this.stopRepaintLoop();
    (_a = this.colorizer) == null ? void 0 : _a.clear();
  }
  status() {
    return `${metricsStorePath(this.app)} \u2014 ${this.lastStatus}`;
  }
  async reload(notify) {
    if (!this.settings.enabled) {
      this.colorizer.clear();
      this.lastStatus = "Heat map disabled.";
      return;
    }
    const data = await readMetricsStore(this.app);
    if (!data) {
      this.colorizer.setIntensities(/* @__PURE__ */ new Map());
      this.lastStatus = 'No readable metrics store. Install Local REST API with MCP and turn on "Note access metrics" in its settings.';
      if (notify) new import_obsidian2.Notice(this.lastStatus);
      return;
    }
    const computed = intensities(data, this.settings);
    this.colorizer.setIntensities(computed);
    this.lastStatus = `${computed.size} note(s) with recorded accesses.`;
    if (notify) new import_obsidian2.Notice(`Metrics heat map: ${this.lastStatus}`);
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.scheduleReload();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  scheduleReload() {
    this.stopReloadTimer();
    const seconds = Math.max(5, this.settings.refreshSeconds);
    this.reloadTimer = window.setInterval(
      () => void this.reload(false),
      seconds * 1e3
    );
    this.registerInterval(this.reloadTimer);
  }
  stopReloadTimer() {
    if (this.reloadTimer === null) return;
    window.clearInterval(this.reloadTimer);
    this.reloadTimer = null;
  }
  /**
   * Re-applies colours every animation frame rather than on a timer.
   *
   * The graph renderer redraws nodes in its own colours every frame it
   * animates, so a periodic timer only wins the race intermittently and the
   * graph visibly pulses between its colours and ours. Running at the same
   * cadence as the renderer keeps ours the last write every frame. The work
   * itself is cheap (a walk over open graph leaves comparing an integer per
   * node), so this is not a meaningful cost even when no graph is open.
   */
  startRepaintLoop() {
    const step = () => {
      this.colorizer.apply();
      this.repaintHandle = window.requestAnimationFrame(step);
    };
    this.repaintHandle = window.requestAnimationFrame(step);
  }
  stopRepaintLoop() {
    if (this.repaintHandle === null) return;
    window.cancelAnimationFrame(this.repaintHandle);
    this.repaintHandle = null;
  }
};
